name: Build with package.json config

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.20.0'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Run make using package.json script
              run: npm run make

            - name: Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: app-${{ matrix.os }}
                  path: |
                      out/make/zip/*
                  retention-days: 30
